{
  "compatibilityLevel": 1550,
  "model": {
    "annotations": [
      {
        "name": "PBI_QueryOrder",
        "value": "[\"covid_data\"]"
      },
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "1"
      },
      {
        "name": "PBIDesktopVersion",
        "value": "2.139.2054.0 (24.12)+334ca1c95b576cc53924655643b0d36f21caac55"
      },
      {
        "name": "PBI_ProTooling",
        "value": "[\"DevMode\"]"
      }
    ],
    "culture": "en-US",
    "cultures": [
      {
        "name": "en-US",
        "linguisticMetadata": {
          "content": {
            "Entities": {
              "covid_data.country_region": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "covid_data",
                    "ConceptualProperty": "Country/Region"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "País / Região": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  }
                ]
              },
              "covid_data.country_region1": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "covid_data",
                    "ConceptualProperty": "country_region"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "País / Região": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  }
                ]
              },
              "covid_data.date": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "covid_data",
                    "ConceptualProperty": "date"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "Data": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  }
                ]
              },
              "covid_data.province_state": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "covid_data",
                    "ConceptualProperty": "province_state"
                  }
                },
                "State": "Generated",
                "Terms": [
                  {
                    "Província / Estado": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  },
                  {
                    "Estado / Província": {
                      "Source": {
                        "Agent": "PowerBI.VisualColumnRename",
                        "Type": "External"
                      },
                      "State": "Suggested",
                      "Weight": 0.9
                    }
                  }
                ]
              },
              "public_covid_data.country_region": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "public covid_data",
                    "ConceptualProperty": "country_region"
                  }
                },
                "State": "Generated"
              },
              "public_covid_data.date": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "public covid_data",
                    "ConceptualProperty": "date"
                  }
                },
                "State": "Generated"
              },
              "public_covid_data.province_state": {
                "Definition": {
                  "Binding": {
                    "ConceptualEntity": "public covid_data",
                    "ConceptualProperty": "province_state"
                  }
                },
                "State": "Generated"
              }
            },
            "Language": "en-US",
            "Version": "2.0.0"
          },
          "contentType": "json"
        }
      }
    ],
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "sourceQueryCulture": "pt-BR",
    "tables": [
      {
        "name": "covid_data",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "8ae6387d-d135-4140-9a23-4fce746133a3",
            "sourceColumn": "id",
            "sourceProviderType": "int",
            "summarizeBy": "sum"
          },
          {
            "name": "fips",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "b26f83be-f16c-4f3a-8c24-3364603f3f1d",
            "sourceColumn": "fips",
            "sourceProviderType": "double",
            "summarizeBy": "sum"
          },
          {
            "name": "admin2",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1a372ac7-d88e-4f3d-b974-ee107387ff52",
            "sourceColumn": "admin2",
            "sourceProviderType": "nvarchar(-1)",
            "summarizeBy": "none"
          },
          {
            "name": "province_state",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "97b89a78-6cfe-4b1c-af76-31a9878aed76",
            "sourceColumn": "province_state",
            "sourceProviderType": "nvarchar(-1)",
            "summarizeBy": "none"
          },
          {
            "name": "country_region",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "264111dd-032d-4a88-8efd-dd7453be6b7c",
            "sourceColumn": "country_region",
            "sourceProviderType": "nvarchar(-1)",
            "summarizeBy": "none"
          },
          {
            "name": "last_update",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "6a5c2c07-db8e-4c56-a14a-c3347c1ba12b",
            "sourceColumn": "last_update",
            "sourceProviderType": "datetime2",
            "summarizeBy": "none"
          },
          {
            "name": "lat",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "ad25aceb-6950-4bf9-9ad4-164d571fb3aa",
            "sourceColumn": "lat",
            "sourceProviderType": "double",
            "summarizeBy": "sum"
          },
          {
            "name": "long_",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "2e00ec82-5c64-46d3-b112-708ee89219ce",
            "sourceColumn": "long_",
            "sourceProviderType": "double",
            "summarizeBy": "sum"
          },
          {
            "name": "confirmed",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "372f6d2e-2833-4a73-a1df-4bb57471ce97",
            "sourceColumn": "confirmed",
            "sourceProviderType": "double",
            "summarizeBy": "sum"
          },
          {
            "name": "deaths",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "cb67f9da-9cd6-4944-812e-aea37db72174",
            "sourceColumn": "deaths",
            "sourceProviderType": "double",
            "summarizeBy": "sum"
          },
          {
            "name": "recovered",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "c1aeca50-9c36-4763-92a6-5a8e85fb3c9b",
            "sourceColumn": "recovered",
            "sourceProviderType": "double",
            "summarizeBy": "sum"
          },
          {
            "name": "active",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "02bc7e7d-28b7-454a-8028-b763e3ab72ec",
            "sourceColumn": "active",
            "sourceProviderType": "double",
            "summarizeBy": "sum"
          },
          {
            "name": "combined_key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b4284daa-0abc-46ac-8f0e-2d1f060e6a60",
            "sourceColumn": "combined_key",
            "sourceProviderType": "nvarchar(-1)",
            "summarizeBy": "none"
          },
          {
            "name": "incident_rate",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "c1019fce-6190-46ec-820f-0833238bd48d",
            "sourceColumn": "incident_rate",
            "sourceProviderType": "double",
            "summarizeBy": "sum"
          },
          {
            "name": "case_fatality_ratio",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "caaf5b4d-e06b-4151-b4c9-4186d362e269",
            "sourceColumn": "case_fatality_ratio",
            "sourceProviderType": "double",
            "summarizeBy": "sum"
          },
          {
            "name": "date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "a00ecdbc-852b-4b2f-89b9-833b034f6cc2",
            "sourceColumn": "date",
            "sourceProviderType": "date",
            "summarizeBy": "none"
          },
          {
            "name": "Province/State",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "68d93349-1e51-4712-b0d7-d61dcae33ef4",
            "sourceColumn": "Province/State",
            "sourceProviderType": "nvarchar(-1)",
            "summarizeBy": "none"
          },
          {
            "name": "Country/Region",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5dca9fce-f11d-499a-b10d-068f060e2edc",
            "sourceColumn": "Country/Region",
            "sourceProviderType": "nvarchar(-1)",
            "summarizeBy": "none"
          },
          {
            "name": "Last Update",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "6177d532-e733-4d8e-9845-861f58b33cf8",
            "sourceColumn": "Last Update",
            "sourceProviderType": "datetime2",
            "summarizeBy": "none"
          },
          {
            "name": "latitude",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "f189ef6e-97cf-4177-8546-3d99fcccfe1c",
            "sourceColumn": "latitude",
            "sourceProviderType": "double",
            "summarizeBy": "sum"
          },
          {
            "name": "longitude",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "45fba875-3195-44ca-a982-dbc1be525baa",
            "sourceColumn": "longitude",
            "sourceProviderType": "double",
            "summarizeBy": "sum"
          },
          {
            "name": "incidence_rate",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "fcb7390b-4f99-48cd-a94d-9b54c38b73d1",
            "sourceColumn": "incidence_rate",
            "sourceProviderType": "double",
            "summarizeBy": "sum"
          },
          {
            "name": "Case-Fatality_Ratio",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "168bf18c-bce2-495d-95e7-42784f020070",
            "sourceColumn": "Case-Fatality_Ratio",
            "sourceProviderType": "double",
            "summarizeBy": "sum"
          },
          {
            "name": "confirmed_adjusted",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "expression": "covid_data[confirmed]/1000",
            "isDataTypeInferred": true,
            "lineageTag": "54ca3252-5681-453d-a0cb-337ffa6224b8",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "deaths_adjusted",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "expression": "covid_data[deaths]/1000",
            "isDataTypeInferred": true,
            "lineageTag": "1eec6588-a83f-4cd8-91d9-bd3b7af56da8",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "recovered_adjusted",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "expression": "covid_data[recovered]/1000",
            "isDataTypeInferred": true,
            "lineageTag": "8c078986-19a5-409e-9828-285250f75828",
            "summarizeBy": "sum",
            "type": "calculated"
          }
        ],
        "lineageTag": "84e63982-d4de-443d-8bf1-cdf97a5c3cbc",
        "partitions": [
          {
            "name": "covid_data",
            "mode": "directQuery",
            "source": {
              "expression": [
                "let",
                "    Source = Value.NativeQuery(PostgreSQL.Database(\"localhost:5432\", \"analista-bi\"), \"select * from public.covid_data where confirmed is not null and confirmed >= 0\", null, [EnableFolding=true]),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(Source,{{\"date\", type date}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      }
    ]
  }
}